name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      # هاد السطر غادي يفك الزحام ديال المكتبات ويحدثهم للنسخة اللي كتمشى مع Flutter 3.19
      - name: Upgrade dependencies
        run: flutter pub upgrade

      - name: Build APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: khenifra-heritage-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
